# Generated by Django 5.2.17 on 2026-09-29 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declared_code', models.CharField(max_length=80)),
                ('roster_version', models.CharField(max_length=80)),
                ('policy_version', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('STARTED', 'Đã bắt đầu'), ('IN_PROGRESS', 'Đang xử lý'), ('CONCLUDED', 'Đã kết thúc'), ('INTERRUPTED', 'Bị gián đoạn')], default='STARTED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('exam_key', models.CharField(max_length=80)),
                ('session_key', models.CharField(max_length=80)),
                ('room_key', models.CharField(max_length=80)),
                ('roster_version', models.CharField(max_length=80)),
                ('policy_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('SETUP', 'Đang chuẩn bị'), ('OPEN', 'Đang tiếp nhận'), ('CLOSED', 'Đã đóng')], default='SETUP', max_length=12)),
                ('policy_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_exam_contexts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='foundation.attempt')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='foundation.examcontext')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='foundation.examcontext'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=80)),
                ('declared_code', models.CharField(db_index=True, max_length=80)),
                ('roster_version', models.CharField(max_length=80)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='foundation.examcontext')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.registration'),
        ),
        migrations.CreateModel(
            name='ReviewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Đang chờ'), ('CLOSED', 'Đã xử lý')], default='OPEN', max_length=12)),
                ('assigned_role', models.CharField(default='REVIEWER', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_cases', to='foundation.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='ContextAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPERATOR', 'Nhân sự tại cửa'), ('REVIEWER', 'Người nhận case')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='foundation.examcontext')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('context', 'user', 'role'), name='one_context_role_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('context', 'roster_version', 'source_key'), name='one_registration_per_roster_version'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('context', 'actor', 'idempotency_key'), name='one_attempt_per_idempotency_key'),
        ),
    ]
