# Generated by Django 5.2.17 on 2026-09-29 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('building', models.CharField(blank=True, max_length=160)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='client_event_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='previous_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.attempt'),
        ),
        migrations.AddField(
            model_name='reviewcase',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcase',
            name='next_action',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='reviewcase',
            name='resolution_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reviewcase',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Đang chờ'), ('IN_REVIEW', 'Đang xử lý'), ('CLOSED', 'Đã xử lý')], default='OPEN', max_length=12),
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('FINALIZED', 'Đã xác nhận'), ('REOPENED', 'Mở lại')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNFINALIZED', 'Chưa chốt'), ('PRESENT_CONFIRMED', 'Có mặt'), ('ABSENT_CONFIRMED', 'Vắng mặt'), ('UNDETERMINED', 'Chưa xác định')], default='UNFINALIZED', max_length=20)),
                ('evidence_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='foundation.attendancereport')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='AssetReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FACE_REFERENCE', 'Ảnh tham chiếu'), ('VERIFICATION', 'Bằng chứng xác minh'), ('MODEL', 'Model AI')], max_length=24)),
                ('storage_key', models.CharField(max_length=240, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECORDED', 'Đã ghi nhận'), ('DISPUTED', 'Đang tranh chấp'), ('VOIDED', 'Đã hủy qua correction')], default='RECORDED', max_length=12)),
                ('confirmed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.attempt')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='foundation.examcontext')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_key', models.UUIDField(unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang dùng'), ('REVOKED', 'Đã thu hồi')], default='ACTIVE', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.device'),
        ),
        migrations.CreateModel(
            name='EntryDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('NOT_APPLICABLE', 'Ngoài phạm vi'), ('ALLOWED', 'Được phép'), ('DENIED', 'Không được phép'), ('UNRESOLVED', 'Chưa kết luận')], default='NOT_APPLICABLE', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.attempt')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.examcontext')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before_state', models.JSONField(default=dict)),
                ('proposed_state', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Đã yêu cầu'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Không duyệt'), ('APPLIED', 'Đã áp dụng')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attendance_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.attendanceresult')),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.checkin')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.examcontext')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.registration')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_corrections', to=settings.AUTH_USER_MODEL)),
                ('entry_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.entrydecision')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('academic_term', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='foundation.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='foundation.exam')),
            ],
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_reports', to='foundation.examsession'),
        ),
        migrations.AddField(
            model_name='examcontext',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.examsession'),
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('APPROVED', 'Đã duyệt'), ('RETIRED', 'Hết hiệu lực')], default='DRAFT', max_length=12)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_versions', to='foundation.examcontext')),
            ],
        ),
        migrations.AddField(
            model_name='examcontext',
            name='active_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_contexts', to='foundation.policyversion'),
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_code', models.CharField(max_length=80)),
                ('reason', models.TextField()),
                ('policy_version', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='foundation.reviewcase')),
            ],
        ),
        migrations.AddField(
            model_name='examcontext',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.room'),
        ),
        migrations.CreateModel(
            name='RosterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80)),
                ('source_format', models.CharField(choices=[('DEMO', 'Dữ liệu giả'), ('CSV', 'CSV'), ('XLSX', 'Excel')], default='DEMO', max_length=8)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Có hiệu lực'), ('SUPERSEDED', 'Đã thay thế')], default='DRAFT', max_length=12)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_batches', to='foundation.examcontext')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examcontext',
            name='active_roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_contexts', to='foundation.rosterbatch'),
        ),
        migrations.AddField(
            model_name='registration',
            name='roster_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.rosterbatch'),
        ),
        migrations.CreateModel(
            name='SyncSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=60)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Đã nhận'), ('APPLIED', 'Đã áp dụng'), ('REJECTED', 'Bị từ chối'), ('REVIEW', 'Cần xem xét')], default='RECEIVED', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.attempt')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.examcontext')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_submissions', to='foundation.device')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationTry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('try_no', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('satisfied', 'Đáp ứng'), ('unmet', 'Không đáp ứng'), ('unavailable', 'Không khả dụng'), ('inconclusive', 'Chưa rõ')], max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('pipeline_version', models.CharField(max_length=80)),
                ('model_version', models.CharField(max_length=80)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_tries', to='foundation.attempt')),
                ('evidence_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.assetreference')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendanceresult',
            constraint=models.UniqueConstraint(fields=('report', 'candidate'), name='one_attendance_result_per_report'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RECORDED', 'DISPUTED'])), fields=('context', 'candidate'), name='one_effective_checkin_per_candidate_context'),
        ),
        migrations.AddConstraint(
            model_name='correction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance_result__isnull', True), ('checkin__isnull', False), ('entry_decision__isnull', True), ('registration__isnull', True)), models.Q(('attendance_result__isnull', True), ('checkin__isnull', True), ('entry_decision__isnull', False), ('registration__isnull', True)), models.Q(('attendance_result__isnull', False), ('checkin__isnull', True), ('entry_decision__isnull', True), ('registration__isnull', True)), models.Q(('attendance_result__isnull', True), ('checkin__isnull', True), ('entry_decision__isnull', True), ('registration__isnull', False)), _connector='OR'), name='correction_has_one_target'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('exam', 'key'), name='one_session_key_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.UniqueConstraint(fields=('session', 'version'), name='one_attendance_report_version'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('context', 'version'), name='one_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='rosterbatch',
            constraint=models.UniqueConstraint(fields=('context', 'version'), name='one_roster_batch_version'),
        ),
        migrations.AddIndex(
            model_name='syncsubmission',
            index=models.Index(fields=['context', 'status', 'received_at'], name='sync_context_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncsubmission',
            constraint=models.UniqueConstraint(fields=('device', 'client_event_id'), name='one_submission_per_device_event'),
        ),
        migrations.AddConstraint(
            model_name='verificationtry',
            constraint=models.UniqueConstraint(fields=('attempt', 'try_no'), name='one_verification_per_try_number'),
        ),
        migrations.AddConstraint(
            model_name='verificationtry',
            constraint=models.CheckConstraint(condition=models.Q(('try_no__gte', 1), ('try_no__lte', 2)), name='verification_try_number_1_or_2'),
        ),
    ]
