# Generated by Django 5.2.17 on 2026-09-29 13:50

from django.db import migrations
import uuid


def backfill_domain_links(apps, schema_editor):
    ExamContext = apps.get_model('foundation', 'ExamContext')
    Exam = apps.get_model('foundation', 'Exam')
    ExamSession = apps.get_model('foundation', 'ExamSession')
    Room = apps.get_model('foundation', 'Room')
    RosterBatch = apps.get_model('foundation', 'RosterBatch')
    PolicyVersion = apps.get_model('foundation', 'PolicyVersion')
    Candidate = apps.get_model('foundation', 'Candidate')
    Registration = apps.get_model('foundation', 'Registration')

    for context in ExamContext.objects.all().iterator():
        exam, _ = Exam.objects.get_or_create(key=context.exam_key, defaults={'title': context.exam_key})
        session, _ = ExamSession.objects.get_or_create(
            exam=exam, key=context.session_key, defaults={'label': context.session_key},
        )
        room, _ = Room.objects.get_or_create(key=context.room_key, defaults={'label': context.room_key})
        roster, _ = RosterBatch.objects.get_or_create(
            context=context, version=context.roster_version,
            defaults={'source_format': 'DEMO', 'status': 'ACTIVE' if context.status == 'OPEN' else 'DRAFT'},
        )
        policy, _ = PolicyVersion.objects.get_or_create(
            context=context, version=context.policy_version,
            defaults={
                'status': 'APPROVED' if context.policy_approved_at else 'DRAFT',
                'approved_at': context.policy_approved_at,
                'approved_by_id': context.policy_approved_by_id,
            },
        )
        context.session_id = session.pk
        context.room_id = room.pk
        context.active_roster_id = roster.pk
        context.active_policy_id = policy.pk
        context.save(update_fields=['session', 'room', 'active_roster', 'active_policy'])

        candidates = {}
        for registration in Registration.objects.filter(context=context).order_by('id').iterator():
            if registration.source_key not in candidates:
                candidates[registration.source_key] = Candidate.objects.create(
                    key=f'CAND-{uuid.uuid4().hex}',
                    is_synthetic=context.key.startswith('CTX-SIM'),
                )
            registration.candidate_id = candidates[registration.source_key].pk
            registration.roster_batch_id = roster.pk
            registration.save(update_fields=['candidate', 'roster_batch'])


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_candidate_course_room_attempt_client_event_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_domain_links, reverse_code=migrations.RunPython.noop),
    ]
