# Generated by Django 5.2.17 on 2026-09-29 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_backfill_domain_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcontext',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.room'),
        ),
        migrations.AlterField(
            model_name='examcontext',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.examsession'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.candidate'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='roster_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foundation.rosterbatch'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='approved_policy_has_actor_and_time'),
        ),
        migrations.AddConstraint(
            model_name='rosterbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('context',), name='one_active_roster_per_context'),
        ),
    ]
