# Generated by Django 5.2.17 on 2026-09-29 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_checkin_unique_per_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_role',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='subject_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='subject_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rosterbatch',
            name='format_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contextassignment',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Nhân sự tại cửa'), ('REVIEWER', 'Người nhận case'), ('ROSTER_MANAGER', 'Quản lý roster'), ('POLICY_APPROVER', 'Duyệt policy'), ('RECONCILER', 'Đối soát'), ('AUDITOR', 'Đọc audit')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['context', 'created_at'], name='audit_context_time_idx'),
        ),
    ]
