# Generated by Django 5.2.17 on 2026-09-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_auditevent_actor_role_auditevent_occurred_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcase',
            name='assigned_role',
            field=models.CharField(default='REVIEWER', max_length=24),
        ),
        migrations.CreateModel(
            name='RosterImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('error_code', models.CharField(max_length=80)),
                ('source_key_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='foundation.rosterbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'row_number'], name='roster_issue_row_idx')],
            },
        ),
    ]
